default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: rails_shield_api_development

test:
  <<: *default
  database: rails_shield_api_test

production:
  <<: *default
  database: rails_shield_api_production
  username: rails_shield_api
  password: <%= ENV["DATABASE_PASSWORD"] %>